### PR TITLE
Feature/fixes

### LINKED ISSUE #7: Handle relative URLs
```
> xctemplate install --url ./CodeSnippet_iOS 
Error: Error(output: "fatal: repository \'./CodeSnippet_iOS\' does not exist\n")
```

### LINKED ISSUE #11: Handle empty CodeSnippets folder
If the user've never created a snippet, the `~/Library/Developer/Xcode/UserData/CodeSnippets` folder does not exist

### PR DESCRIPTION
**Pull request by gaetanzanella**
- Fixed #7 
- Fixed #11

### CODE REVIEW

File: Sources/XCResource/XCSnippet/XCSnippetLibrary.swift [hunk 1]
```diff
@@ -3,28 +3,33 @@ import Foundation
...
+    private let fileManager: FileManager
     private let snippetFileManager: XCSnippetFileManager
     private let downloader: XCSnippetsDownloader
     private let urlProvider: XCSnippetFolderURLProviding
 
     // MARK: - Life Cycle
 
     public convenience init() {
-        let snippetFileManager = XCSnippetFileManager(fileManager: .default)
+        let fileManager = FileManager.default
```
Comment (alexandre-pod) [inline Sources/XCResource/XCSnippet/XCSnippetLibrary.swift]: You can move it into the init with a default value, with that it will still be configurable with the convenience init

File: Sources/XCResource/XCTemplate/XCTemplateLibrary.swift [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+                  downloader: XCTemplatesDownloader,
+                  urlProvider: XCTemplateFolderURLProviding) {
+        self.fileManager = fileManager
+        self.downloader = downloader
+        self.urlProvider = urlProvider
+    }
+
+    public convenience init() {
+        let fileManager = XCTemplateFileManager(
+            fileManager: .default
```
Comment (alexandre-pod) [inline Sources/XCResource/XCTemplate/XCTemplateLibrary.swift]: You can pass the `.default` file manager as a parameter with default value of the convenience init

File: Sources/CLI/XCSnippet/RemoveSnippetsCommand.swift [hunk 3]
```diff
@@ -20,14 +20,6 @@ struct RemoveSnippetsCommand: ParsableCommand {
...
-        if let namespace = namespace {
-            let xcnamespace = XCSnippetNamespace(namespace)
-            try cli.removeSnippets(for: xcnamespace)
-        } else {
-            let namespaces = try cli.snippetNamespaces()
-            try namespaces.forEach { namespace in
-                try cli.removeSnippets(for:namespace)
-            }
-        }
+        try cli.removeSnippets(namespace: namespace)
```
Comment (alexandre-pod) [inline Sources/CLI/XCSnippet/RemoveSnippetsCommand.swift]: You no longer need the `cli` variable

File: Sources/CLI/XCSnippet/RemoveSnippetsCommand.swift [hunk 4]
```diff
@@ -19,6 +19,15 @@ struct RemoveSnippetsCommand: ParsableCommand {
...
-        try XCSnippetCLI().removeSnippets(for: XCSnippetNamespace(namespace))
+        let cli = XCSnippetCLI()
+        if let namespace = namespace {
+            let xcnamespace = XCSnippetNamespace(namespace)
+            try cli..removeSnippets(for: xcnamespace)
+        } else {
+            let namespaces = try cli.snippetNamespaces()
+            try namespaces.forEach { namespace in
+                try cli..removeSnippets(for:namespace)
+            }
```
Comment (alexandre-pod) [inline Sources/CLI/XCSnippet/RemoveSnippetsCommand.swift]: If I understood correctly, this will also removes the snippets without namespace. This seems risky as It will delete the custom snippets made by a user, and this only by forgetting the namespace argument.
Maybe in this case inform the user that ALL snippets will be deleted, including the snippets without namespace.

A loss of personal data will not be a great experience by a user

File: Sources/XCResource/XCTemplate/URLInputParser.swift [hunk 5]
```diff
@@ -0,0 +1,46 @@
+//
+//  File.swift
+//  
+//
+//  Created by Gaétan Zanella on 21/07/2021.
+//
```
Comment (alexandre-pod) [inline Sources/XCResource/XCTemplate/URLInputParser.swift]: To remove, or update "File.swift"
`XCSnippetsDownloader.swift` has the same issue

**Review by alexandre-pod — CHANGES_REQUESTED** [review]
You did not mention the update of the command `xcresource snippet remove`, which now works without arguments.

**Review by alexandre-pod — APPROVED** [review]
